### ISSUE TITLE
Add better expectations examples

### ISSUE THREAD

**Issue by mcbridem** [usnews/smoketest#17]
We should at least document this:

```
## Canonical check
-   directive: check
    url: https://www.usnews.com
    html:
    -   selector: link[rel="canonical"]
        attribute: href
        equals: https://www.usnews.com
```

There's no mention of this `attribute` key in the repository currently, as far as I can tell.

Adding some actual example expectations files might also be nice.
