### ISSUE TITLE
Add ability to test SSL certificate expiries

### ISSUE THREAD

**Issue by mcbridem** [usnews/smoketest#36]
It would be nice if Smoketest could check SSL certificate expiries and report if the expiration is within a certain number of days. Perhaps something like this:

```yaml
-   directive: check
    host: www.theatlantic.com
    ssl:
        cert_expiry: 15
```

**Comment by mcbridem** [comment]
After some discussion and playing around with the relevant code, it seems like we want something more like this:

```yaml
-   directive: check2
    host: www.theatlantic.com
    ssl_cert:
        expiry_days_away: 15
```

This would be a new directive type that would not be so tied to the idea of always having a URL or having URLs to test. And this new directive type would not be so tied to the idea of always having a traditional HTTP `response` object returned.
